ccflags-y += -Idrivers/media/platform/msm/camera_v2-ebz
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ebz/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ebz/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
