/* drivers/sharp/shtps/sy3000/tm2945-001/shtps_cfg_tm2945-001.h
 *
 * Copyright (c) 2014, Sharp. All rights reserved.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
#ifndef __SHTPS_CFG_TM2945_001_H__
#define __SHTPS_CFG_TM2945_001_H__

/* ===================================================================================
 * [ Debug ]
 */
#define SHTPS_DEVELOP_MODE_ENABLE

#ifdef	SHTPS_DEVELOP_MODE_ENABLE
	//#define SHTPS_PERFORMANCE_CHECK_ENABLE
	//#define SHTPS_LOG_SEQ_ENABLE
	//#define SHTPS_LOG_SPIACCESS_SEQ_ENABLE
	#define SHTPS_LOG_DEBUG_ENABLE
	#define	SHTPS_LOG_EVENT_ENABLE
	#define	SHTPS_MODULE_PARAM_ENABLE
	#define	SHTPS_DEBUG_VARIABLE_DEFINES
	#define SHTPS_CREATE_KOBJ_ENABLE
#endif

#define	SHTPS_LOG_ERROR_ENABLE

#ifdef SHTPS_LOG_EVENT_ENABLE
	#define SHTPS_LOG_OUTPUT_SWITCH_ENABLE
#endif /* #if defined( SHTPS_LOG_EVENT_ENABLE ) */

#if defined(SHTPS_PERFORMANCE_CHECK_ENABLE)
	#define SHTPS_PERFORMANCE_CHECK_PIN_ENABLE
	//#define SHTPS_PERFORMANCE_TIME_LOG_ENABLE
#endif /* SHTPS_PERFORMANCE_CHECK_ENABLE */

/* ===================================================================================
 * [ Diag ]
 */
#ifdef	SHTPS_FACTORY_MODE_ENABLE
	#undef	SHTPS_BOOT_FWUPDATE_ENABLE
	#undef	SHTPS_BOOT_FWUPDATE_FORCE_UPDATE
	#define	SHTPS_FMODE_GESTURE_ENABLE
	#define SHTPS_TPIN_CHECK_ENABLE
#else
	#define	SHTPS_BOOT_FWUPDATE_ENABLE
	#undef	SHTPS_BOOT_FWUPDATE_FORCE_UPDATE
	#undef	SHTPS_FMODE_GESTURE_ENABLE
	#undef	SHTPS_TPIN_CHECK_ENABLE
#endif

#define SHTPS_CHECK_CRC_ERROR_ENABLE
#define	SHTPS_SMEM_BASELINE_ENABLE

#define SHTPS_DIAGPOLL_TIME							100


/* ===================================================================================
 * [ Firmware update ]
 */
#define SHTPS_MULTI_FW_ENABLE
#define SHTPS_CHECK_HWID_ENABLE
#define SHTPS_BOOT_FWUPDATE_ONLY_ON_HANDSET
#define SHTPS_SPI_FWBLOCKWRITE_ENABLE
#define	SHTPS_FWUPDATE_BUILTIN_ENABLE

#if defined(SHTPS_CHECK_HWID_ENABLE)
	#define SHTPS_GET_HW_VERSION_RET_ES_0		0
	#define SHTPS_GET_HW_VERSION_RET_ES_0_5		4
	#define SHTPS_GET_HW_VERSION_RET_ES_1		2
	#define SHTPS_GET_HW_VERSION_RET_PP_1		6
	#define SHTPS_GET_HW_VERSION_RET_PP_2		1
	#define SHTPS_GET_HW_VERSION_RET_RESERVE1	5
	#define SHTPS_GET_HW_VERSION_RET_RESERVE2	3
	#define SHTPS_GET_HW_VERSION_RET_MP			7
	#define SHTPS_GET_HW_VERSION_RET_UNKNOWN	0xFF
#endif /* SHTPS_CHECK_HWID_ENABLE */

#if defined(SHTPS_MULTI_FW_ENABLE)
	#include "tm2945-001/shtps_fw_tm2945-001_es1.h"
	#include "tm2945-001/shtps_fw_tm2945-001.h"
	
	typedef struct {
		unsigned char		hwrev;
		const unsigned char	*data;
		unsigned short		size;
		unsigned short		ver;
		char				*name;
	} shtps_multi_fw_info_t;
	
	static const shtps_multi_fw_info_t SHTPS_MULTI_FW_INFO_TBL[] = {
		{ SHTPS_GET_HW_VERSION_RET_ES_0,   tps_fw_data_es1, SHTPS_FWSIZE_NEWER_ES1, SHTPS_FWVER_NEWER_ES1, "ES1"    },
		{ SHTPS_GET_HW_VERSION_RET_ES_0_5, tps_fw_data_es1, SHTPS_FWSIZE_NEWER_ES1, SHTPS_FWVER_NEWER_ES1, "ES1"    },
		{ SHTPS_GET_HW_VERSION_RET_ES_1,   tps_fw_data_es1, SHTPS_FWSIZE_NEWER_ES1, SHTPS_FWVER_NEWER_ES1, "ES1"    },
		{ SHTPS_GET_HW_VERSION_RET_PP_1,   tps_fw_data,     SHTPS_FWSIZE_NEWER,     SHTPS_FWVER_NEWER    , "NORMAL" },
		{ SHTPS_GET_HW_VERSION_RET_PP_2,   tps_fw_data,     SHTPS_FWSIZE_NEWER,     SHTPS_FWVER_NEWER    , "NORMAL" },
		{ SHTPS_GET_HW_VERSION_RET_MP,     tps_fw_data,     SHTPS_FWSIZE_NEWER,     SHTPS_FWVER_NEWER    , "NORMAL" },
		{ SHTPS_GET_HW_VERSION_RET_UNKNOWN,tps_fw_data,     SHTPS_FWSIZE_NEWER,     SHTPS_FWVER_NEWER    , "NORMAL" },
	};
	static const int SHTPS_MULTI_FW_INFO_SIZE = sizeof(SHTPS_MULTI_FW_INFO_TBL) / sizeof(shtps_multi_fw_info_t);
#else
	#include "tm2945-001/shtps_fw_tm2945-001.h"
#endif /* SHTPS_MULTI_FW_ENABLE */


/* ===================================================================================
 * [ Model specifications ]
 */
#define CONFIG_SHTPS_SY3000_PANEL_SIZE_X		1080
#define CONFIG_SHTPS_SY3000_PANEL_SIZE_Y		1920
#define CONFIG_SHTPS_SY3000_LCD_SIZE_X			CONFIG_SHTPS_SY3000_PANEL_SIZE_X
#define CONFIG_SHTPS_SY3000_LCD_SIZE_Y			CONFIG_SHTPS_SY3000_PANEL_SIZE_Y
//#define CONFIG_SHTPS_SY3000_FACETOUCH_DETECT
//#define CONFIG_SHTPS_SY3000_FACETOUCH_OFF_DETECT
#define CONFIG_SHTPS_SY3000_POSITION_OFFSET
#define CONFIG_SHTPS_SY3000_ALWAYS_ACTIVEMODE
//#define CONFIG_SHTPS_SY3000_FLIP_CHANGE_HANDLE

#define SHTPS_IRQ_LEVEL_ENABLE
#define SHTPS_SYSTEM_BOOT_MODE_CHECK_ENABLE
#define SHTPS_SYSTEM_HOT_STANDBY_ENABLE
#define SHTPS_IRQ_LOADER_CHECK_INT_STATUS_ENABLE

//#define SHTPS_PHYSICAL_KEY_ENABLE
//#define SHTPS_HOVER_DETECT_ENABLE
//#define SHTPS_PEN_DETECT_ENABLE
#define SHTPS_LPWG_MODE_ENABLE

#if defined( SHTPS_LPWG_MODE_ENABLE )
	#define SHTPS_HOST_LPWG_MODE_ENABLE
#endif /* SHTPS_LPWG_MODE_ENABLE */

#if defined( CONFIG_SHTPS_SY3000_ALWAYS_ACTIVEMODE )
	#define SHTPS_LOW_POWER_MODE_ENABLE
#endif /* #if defined( CONFIG_SHTPS_SY3000_ALWAYS_ACTIVEMODE ) */

#define SHTPS_QOS_LATENCY_DEF_VALUE	 			34

//#define SHTPS_BASELINE_OFFSET_DISABLE_WAIT_ENABLE

/* ===================================================================================
 * [ Firmware control ]
 */
#define SHTPS_FWDATA_BLOCK_SIZE_MAX					0xFFFF
#define SHTPS_BOOTLOADER_ACK_TMO					1000
#define SHTPS_FWTESTMODE_ACK_TMO					1000
#define SHTPS_F54_COMMAND_WAIT_POLL_COUNT			30
#define SHTPS_F54_COMMAND_WAIT_POLL_INTERVAL		10
#define SHTPS_PDT_PAGE_SIZE_MAX						4
#define SHTPS_PDT_READ_RETRY_COUNT					5
#define SHTPS_PDT_READ_RETRY_INTERVAL				200
#define SHTPS_FLASH_ERASE_WAIT_MS					2000

#define SHTPS_POS_SCALE_X(ts)	(((CONFIG_SHTPS_SY3000_PANEL_SIZE_X) * 10000) / ts->map.fn12.ctrl.maxXPosition)
#define SHTPS_POS_SCALE_Y(ts)	(((CONFIG_SHTPS_SY3000_PANEL_SIZE_Y) * 10000) / ts->map.fn12.ctrl.maxYPosition)


/* ===================================================================================
 * [ Hardware specifications ]
 */
#define SHTPS_GPIO_TPIN_NO					96
#define SHTPS_SY3X00_GPIO_RST				29
#define SHTPS_SY3X00_GPIO_IRQ				77
#define SHTPS_SY3X00_SPI_CLOCK				1100000

#define SHTPS_SPI_BLOCKACCESS_ENABLE

#define	SHTPS_SPI_FAST_CLOCK_ENABLE
#define	SHTPS_SPI_FAST_FW_TRANSFER_ENABLE

#ifdef	SHTPS_SPI_FAST_CLOCK_ENABLE
	#define TPS_SPI_R_CLOCK			3200000
	#define TPS_SPI_W_CLOCK			3200000
	#define TPS_SPI_R_BYTE_DELAY	20
	#define TPS_SPI_W_BYTE_DELAY	5
	#define TPS_SPI_R_TANS_WAIT		5
	#define TPS_SPI_W_TANS_WAIT		5
#else
	#define TPS_SPI_R_CLOCK			1100000
	#define TPS_SPI_W_CLOCK			600000
	#define TPS_SPI_R_BYTE_DELAY	20
	#define TPS_SPI_W_BYTE_DELAY	0
	#define TPS_SPI_R_TANS_WAIT		40
	#define TPS_SPI_W_TANS_WAIT		65
#endif

#ifdef	SHTPS_SPI_BLOCKACCESS_ENABLE
	#define SHTPS_SY3X00_FINGER_SPIREAD_CNT		2
#else
	#define SHTPS_SY3X00_FINGER_SPIREAD_CNT		0
#endif

#define	SHTPS_SY3X00_SPIBLOCK_BUFSIZE			(SHTPS_TM_TXNUM_MAX * 2)
#define SHTPS_SY3X00_SPIBLOCKWRITE_BUFSIZE		0x10

#define SHTPS_SPI_RETRY_COUNT					5
#define SHTPS_SPI_RETRY_WAIT					5

#define SHTPS_STARTUP_MIN_TIME					300
#define SHTPS_POWERON_WAIT_MS					400
#define SHTPS_POWEROFF_WAIT_MS					10
#define SHTPS_HWRESET_TIME_US					1
#define SHTPS_HWRESET_AFTER_TIME_MS				1
#define SHTPS_HWRESET_WAIT_MS					290
#define SHTPS_SWRESET_WAIT_MS					300
#define SHTPS_RESET_BOOTLOADER_WAIT_MS			400
#define SHTPS_SLEEP_OUT_WAIT_US					67500


/* ===================================================================================
 * [ Performance ]
 */
#ifdef CONFIG_SHSYS_CUST_PERFLOCK
	#define SHTPS_CPU_CLOCK_CONTROL_ENABLE
#endif /* CONFIG_SHSYS_CUST_PERFLOCK */

#define SHTPS_CPU_IDLE_SLEEP_CONTROL_ENABLE
#define SHTPS_CPU_SLEEP_CONTROL_FOR_FWUPDATE_ENABLE


/* ===================================================================================
 * [ Standard ]
 */
#define	SHTPS_ASYNC_OPEN_ENABLE				// delete
//#define SHTPS_VKEY_INVALID_AREA_ENABLE	// delete
//#define SHTPS_BTLOADER_VER_ENABLE			// delete
//#define SHTPS_SPICLOCK_CONTROL_ENABLE		// delete
#define SHTPS_SY_REGMAP_BASE3				// delete
#define SHTPS_IRQ_LINKED_WITH_IRQWAKE_ENABLE
#define SHTPS_PDT_READ_RETRY_ENABLE
#define SHTPS_FAILSAFE_ENABLE				// delete
#define SHTPS_INPUT_POWER_MODE_CHANGE_ENABLE
#define SHTPS_GUARANTEE_SPI_ACCESS_IN_WAKE_ENABLE
#define SHTPS_TOUCHCANCEL_BEFORE_FORCE_TOUCHUP_ENABLE
#define SHTPS_WAKEUP_FAIL_TOUCH_EVENT_REJECTION_ENABLE


/* ===================================================================================
 * [ Host functions ]
 */
#define SHTPS_DRAG_STEP_ENABLE
//#define SHTPS_CHARGER_ARMOR_ENABLE
//#define SHTPS_CLING_REJECTION_ENABLE
//#define SHTPS_EDGE_POS_ADJUST_ENABLE
//#define SHTPS_MULTI_HOVER_SELECT_ENABLE
#define SHTPS_SPI_AVOID_BLOCKREAD_FAIL

#define SHTPS_FINGER_ABSORPTION_PROVISION_ENABLE
#define SHTPS_PROXIMITY_SUPPORT_ENABLE
#define SHTPS_ACTIVE_SLEEP_WAIT_ALWAYS_ENABLE
#define SHTPS_PINCHOUT_FAIL_FLICK_RESOLV_ENABLE
#define SHTPS_FINGER_WIDTH_MODERATION_ENABLE
#define SHTPS_EDGE_FAIL_TOUCH_REJECTION_ENABLE
#define SHTPS_GRIP_FAIL_TOUCH_REJECTION_ENABLE
#define SHTPS_DIAGONAL_GHOST_CHECK_ENABLE
#define SHTPS_DRAG_SMOOTH_ENABLE
#define SHTPS_SHIFT_EDGE_INWARD_ENABLE
#define SHTPS_DYNAMIC_RESET_CONTROL_ENABLE
#define SHTPS_LGM_SPLIT_TOUCH_COMBINING_ENABLE
//#define SHTPS_REPORT_TOOL_TYPE_LOCK_ENABLE
//#define SHTPS_GHOST_REJECTION_ENABLE
//#define SHTPS_HOVER_REJECT_ENABLE
//#define SHTPS_COAXIAL_GHOST_REJECTION_ENABLE
#define SHTPS_PINCH_FAIL_RESPONSE_REJECTION_ENABLE
#define SHTPS_PINCHOUT_OUTSET_DISTORT_REJECTION_ENABLE
#define SHTPS_TOP_EDGE_FAIL_TOUCH_REJECTION_ENABLE

#if defined(SHTPS_HOVER_DETECT_ENABLE)
	#define SHTPS_HOVER_DETECT_FAIL_RESOLV_ENABLE
	#define SHTPS_FORCECAL_AFTER_HOVERSETTING_ENABLE
	#define SHTPS_HOVER_HOST_JITTER_FILTER_ENABLE
	#define SHTPS_HOVER_EDGE_LOST_RESOLV_ENABLE
#endif /* SHTPS_HOVER_DETECT_ENABLE */

#if defined(SHTPS_PHYSICAL_KEY_ENABLE)
	#define SHTPS_FINGER_KEY_EXCLUDE_ENABLE
	
	#if defined(SHTPS_PROXIMITY_SUPPORT_ENABLE)
		#define SHTPS_KEY_PROXIMITY_ASYNC_CHECK_ENABLE
	#endif /* SHTPS_PROXIMITY_SUPPORT_ENABLE */
#endif /* SHTPS_PHYSICAL_KEY_ENABLE */

#if defined(SHTPS_PEN_DETECT_ENABLE)
	#define SHTPS_PEN_SCREEN_EDGE_DISABLE
	#define SHTPS_PEN_EVENT_FAIL_CONTINUE_REJECT_ENABLE
	#define SHTPS_PEN_POS_JUMP_REJECT_ENABLE
	#define SHTPS_MULTITOUCH_PEN_GHOST_REJECTION_ENABLE
#endif /* SHTPS_PEN_DETECT_ENABLE */

#if defined(SHTPS_BOOT_FWUPDATE_FORCE_UPDATE)
	#undef SHTPS_BOOT_FWUPDATE_ONLY_ON_HANDSET
#endif /* SHTPS_BOOT_FWUPDATE_FORCE_UPDATE */

#if defined(SHTPS_LPWG_MODE_ENABLE)
	#define SHTPS_LPWG_CHANGE_SWIPE_DISTANCE_ENABLE
	#define SHTPS_LPWG_GRIP_SUPPORT_ENABLE
	#define SHTPS_LPWG_ALLOWED_SWIPES_ENABLE
#endif /* SHTPS_LPWG_MODE_ENABLE */

#if defined(SHTPS_EDGE_FAIL_TOUCH_REJECTION_ENABLE) && defined(SHTPS_PHYSICAL_KEY_ENABLE)
	#define SHTPS_TOUCHKEY_FAIL_TOUCH_REJECTION_ENABLE
#endif /* SHTPS_EDGE_FAIL_TOUCH_REJECTION_ENABLE && SHTPS_PHYSICAL_KEY_ENABLE */

#if defined( SHTPS_DYNAMIC_RESET_CONTROL_ENABLE )
	//#define SHTPS_DYNAMIC_RESET_ESD_ENABLE
#endif /* SHTPS_DYNAMIC_RESET_CONTROL_ENABLE */

/* ===================================================================================
 * [ Local MACRO ]
 */
#if defined( SHTPS_DEVELOP_MODE_ENABLE )
	#define SHTPS_PARAM_DEF(name, val) \
		static int name = val; \
		module_param(name, int, S_IRUGO | S_IWUSR);
#else
	#define SHTPS_PARAM_DEF(name, val) \
		const static int name = val;
#endif /* SHTPS_DEVELOP_MODE_ENABLE */

/* ===================================================================================
 * [ Parameters ]
 */
/* -----------------------------------------------------------------------------------
 */
SHTPS_PARAM_DEF( SHTPS_SLEEP_IN_WAIT_MS, 	30  );
SHTPS_PARAM_DEF( SHTPS_SLEEP_OUT_WAIT_MS, 	0  );
SHTPS_PARAM_DEF( SHTPS_VEILVIEW_PATTERN, 	SHTPS_VEILVIEW_PATTERN_MONOCHROME_1H);

/* -----------------------------------------------------------------------------------
 */
SHTPS_PARAM_DEF(SHTPS_SY3X00_SPI_CLOCK_READ_SPEED,		TPS_SPI_R_CLOCK);
SHTPS_PARAM_DEF(SHTPS_SY3X00_SPI_CLOCK_WRITE_SPEED,		TPS_SPI_W_CLOCK);
SHTPS_PARAM_DEF(SHTPS_SY3X00_SPI_CLOCK_READ_WAIT,		TPS_SPI_R_BYTE_DELAY);
SHTPS_PARAM_DEF(SHTPS_SY3X00_SPI_CLOCK_WRITE_WAIT,		TPS_SPI_W_BYTE_DELAY);
SHTPS_PARAM_DEF(SHTPS_SY3X00_SPI_TANSACTION_READ_WAIT,	TPS_SPI_R_TANS_WAIT);
SHTPS_PARAM_DEF(SHTPS_SY3X00_SPI_TANSACTION_WRITE_WAIT,	TPS_SPI_W_TANS_WAIT);
SHTPS_PARAM_DEF(SHTPS_TOUCH_PERFORMANCE_UP_MODE,		1);

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_DRAG_STEP_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_DRAG_DIR_FIX_CNT, 				3  );
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_VAL_X_ZERO, 			4  );
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_VAL_X_1ST, 			8  );
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_VAL_X_2ND, 			1  );
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_VAL_X_1ST_MULTI, 	12 );
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_VAL_X_2ND_MULTI, 	1  );
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_VAL_Y_ZERO, 			4  );
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_VAL_Y_1ST, 			8  );
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_VAL_Y_2ND, 			1  );
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_VAL_Y_1ST_MULTI, 	12 );
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_VAL_Y_2ND_MULTI, 	1  );
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_RETURN_TIME_ZERO, 	250);
	SHTPS_PARAM_DEF( SHTPS_DRAG_THRESH_RETURN_TIME, 		250);
#endif /* SHTPS_DRAG_STEP_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( CONFIG_SHTPS_SY3000_FACETOUCH_DETECT ) || defined( CONFIG_SHTPS_SY3000_FACETOUCH_OFF_DETECT )
	SHTPS_PARAM_DEF( SHTPS_FINGER_WIDTH_PALMDET, 			15  );
	SHTPS_PARAM_DEF( SHTPS_FINGER_WIDTH_FUZZ, 				0   );
	SHTPS_PARAM_DEF( SHTPS_FINGER_WIDTH_MIN, 				1   );
	SHTPS_PARAM_DEF( SHTPS_FINGER_WIDTH_MAX, 				8   );
	SHTPS_PARAM_DEF( SHTPS_LOS_SINGLE, 						0x05);
	SHTPS_PARAM_DEF( SHTPS_LOS_MULTI, 						0x0D);
#else
	#define SHTPS_FINGER_WIDTH_PALMDET (15)
	#define SHTPS_FINGER_WIDTH_MIN     (1)
#endif /* CONFIG_SHTPS_SY3000_FACETOUCH_DETECT || CONFIG_SHTPS_SY3000_FACETOUCH_OFF_DETECT */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_CHARGER_ARMOR_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_CHARGER_ARMOR_STRENGTH_DEFAULT, 	0x30);
	SHTPS_PARAM_DEF( SHTPS_CHARGER_ARMOR_STRENGTH, 			0x40);
#endif /* SHTPS_CHARGER_ARMOR_ENABLE */


/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_CPU_CLOCK_CONTROL_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_ENABLE_TIME_MS, 	50);
#endif /* SHTPS_CPU_CLOCK_CONTROL_ENABLE */


/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_HOVER_DETECT_ENABLE)
	#define SHTPS_HOVER_CTRL_BASE_ADR					0x00
	#define SHTPS_HOVER_CTRL_BASE_ADR_A1				0x09
	SHTPS_PARAM_DEF( SHTPS_HOVER_THRESH_FOR_ADC_OLD, 	0x2e);
	SHTPS_PARAM_DEF( SHTPS_HOVER_THRESH_FOR_ADC, 		0x40);
#endif /* SHTPS_HOVER_DETECT_ENABLE */


/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_HOVER_DETECT_FAIL_RESOLV_ENABLE)
	#define SHTPS_HOVER_HIST_MAX							10
	#define SHTPS_HOVER_CENTER_HIST_MAX						200
	SHTPS_PARAM_DEF( SHTPS_HOVER_TU_DELAY_TIME_MS, 			0  );
	SHTPS_PARAM_DEF( SHTPS_HOVER_INFO_EFFECT_TIME_MS, 		200);
	SHTPS_PARAM_DEF( SHTPS_HOVER_CENTER_INFO_EFFECT_TIME_MS,200);
	SHTPS_PARAM_DEF( SHTPS_EDGE_HOVER_FAIL_RANGE_X, 		50 );
	SHTPS_PARAM_DEF( SHTPS_EDGE_HOVER_FAIL_RANGE_Y, 		35 );
	SHTPS_PARAM_DEF( SHTPS_HOVER_HIST_COUNT_MAX, 			5  );
	SHTPS_PARAM_DEF( SHTPS_HOVER_IGNORE_WX_MIN, 			-1 );
	SHTPS_PARAM_DEF( SHTPS_HOVER_IGNORE_WX_MAX, 			-1 );
	SHTPS_PARAM_DEF( SHTPS_HOVER_IGNORE_WY_MIN, 			-1 );
	SHTPS_PARAM_DEF( SHTPS_HOVER_IGNORE_WY_MAX, 			-1 );
	SHTPS_PARAM_DEF( SHTPS_HOVER_EDGE_LOST_RESOLV_DISABLE, 	0  );
	SHTPS_PARAM_DEF( hover_debug_log_enable, 				0  );
	SHTPS_PARAM_DEF( stylus_detect_is_hover_event_enable, 	1  );
	SHTPS_PARAM_DEF( hover_report_info_calc_type, 			0  );
#endif /* SHTPS_HOVER_DETECT_FAIL_RESOLV_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_EDGE_POS_ADJUST_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_EDGE_DISABLE_AREA_OFFSET_X, 	0);
	SHTPS_PARAM_DEF( SHTPS_EDGE_ADJUST_AREA_OFFSET_X, 	0);
	SHTPS_PARAM_DEF( SHTPS_EDGE_DISABLE_AREA_OFFSET_Y, 	0);
	SHTPS_PARAM_DEF( SHTPS_EDGE_ADJUST_AREA_OFFSET_Y, 	0);
#endif /* SHTPS_EDGE_POS_ADJUST_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_MULTI_HOVER_SELECT_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_MULTI_HOVER_EDGE_FAIL_RANGE_X, 	100);
	SHTPS_PARAM_DEF( SHTPS_MULTI_HOVER_DIFF_THRESH_X, 		150);
#endif /* SHTPS_MULTI_HOVER_SELECT_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_LPWG_MODE_ENABLE)
	#define SHTPS_LPWG_REPORT_WG_ONLY						0x02
	#define SHTPS_LPWG_F12_CTRL08_BUFF_SIZE					15
	#define SHTPS_LPWG_F12_CTRL18_BUFF_SIZE					9

	#if defined( SHTPS_HOST_LPWG_MODE_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_HOST_LPWG_ENABLE, 				0);
		SHTPS_PARAM_DEF( SHTPS_LPWG_SWIPE_DIST_THRESHOLD, 		300);
		SHTPS_PARAM_DEF( SHTPS_LPWG_SWIPE_CHECK_TIME_MS, 		500);
	#endif /* SHTPS_HOST_LPWG_MODE_ENABLE */

	#if defined(SHTPS_LPWG_CHANGE_SWIPE_DISTANCE_ENABLE)
		SHTPS_PARAM_DEF( SHTPS_LPWG_SWIPE_MINIMUM_DISTANCE, 	0x19);
	#endif /* SHTPS_LPWG_CHANGE_SWIPE_DISTANCE_ENABLE */

	#if defined(SHTPS_LPWG_ALLOWED_SWIPES_ENABLE)
		SHTPS_PARAM_DEF( SHTPS_LPWG_ALLOWED_SWIPES,				0x00);
	#endif /* SHTPS_LPWG_ALLOWED_SWIPES_ENABLE */

	SHTPS_PARAM_DEF( SHTPS_LPWG_ENABLE_GESTURE, 			0x02);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_INTERVAL_DEF, 			0x01);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_INTERVAL, 				0x05);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_WAKEUP_THRESHOLD_DEF, 	0x28);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_WAKEUP_THRESHOLD, 		0x28);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_HOLDOFF_DEF, 			0x05);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_HOLDOFF, 				0x00);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_CTL, 					0x02);
	SHTPS_PARAM_DEF( SHTPS_LPWG_MAX_ACTIVE_DURATION, 		0x01);
	SHTPS_PARAM_DEF( SHTPS_LPWG_MAX_ACTIVE_DURATION_TIME, 	0x05);
	SHTPS_PARAM_DEF( SHTPS_LPWG_RX_CLIP_LO, 				0x00);
	SHTPS_PARAM_DEF( SHTPS_LPWG_RX_CLIP_HI, 				0x00);
	SHTPS_PARAM_DEF( SHTPS_LPWG_TX_CLIP_LO, 				0x3F);
	SHTPS_PARAM_DEF( SHTPS_LPWG_TX_CLIP_HI, 				0x3F);
	SHTPS_PARAM_DEF( SHTPS_LPWG_REPORT_BEYOND_ACTIVE_AREA, 	0x00);
	SHTPS_PARAM_DEF( SHTPS_LPWG_QOS_LATENCY_DEF_VALUE, 		SHTPS_QOS_LATENCY_DEF_VALUE);
	SHTPS_PARAM_DEF( SHTPS_LPWG_BLOCK_TIME_MAX_MS, 			2000);
	SHTPS_PARAM_DEF( SHTPS_LPWG_MIN_NOTIFY_INTERVAL, 		1000);
	SHTPS_PARAM_DEF( SHTPS_LPWG_MODE_ON_AFTER_SLEEP_ENABLE, 0);
	SHTPS_PARAM_DEF( SHTPS_LPWG_MODE_ON_AFTER_REZERO_ENABLE,0);
	SHTPS_PARAM_DEF( SHTPS_LPWG_SET_FORCE_UPDATE_ENABLE,	0);

	#if defined(SHTPS_PROXIMITY_SUPPORT_ENABLE)
		#include <sharp/proximity.h>
		SHTPS_PARAM_DEF( SHTPS_LPWG_PROXIMITY_SUPPORT_ENABLE, 	1);
		SHTPS_PARAM_DEF( SHTPS_LPWG_MIN_NOTIFY_CANCEL_INTERVAL, 800);
		SHTPS_PARAM_DEF( SHTPS_LPWG_PROXIMITY_CHECK_PREWAIT, 	100);
	#endif /* SHTPS_PROXIMITY_SUPPORT_ENABLE */
#endif /* SHTPS_LPWG_MODE_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_PHYSICAL_KEY_ENABLE)
	#if defined(SHTPS_PROXIMITY_SUPPORT_ENABLE)
		#include <sharp/proximity.h>
		SHTPS_PARAM_DEF( SHTPS_KEY_PROXIMITY_SUPPORT_ENABLE, 	1);
	#endif /* SHTPS_PROXIMITY_SUPPORT_ENABLE */
#endif /* SHTPS_PHYSICAL_KEY_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_FINGER_KEY_EXCLUDE_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_KEY_DISABLE_EFFECT_AREA, 	100);
	SHTPS_PARAM_DEF( SHTPS_KEY_DISABLE_TIME_MS, 		200);
	SHTPS_PARAM_DEF( SHTPS_TOUCH_DISABLE_TIME_MS, 		200);
#endif /* SHTPS_FINGER_KEY_EXCLUDE_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_FORCECAL_AFTER_HOVERSETTING_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_FORCECAL_AFTER_HOVERSETTING_WAIT, 20);
#endif /* SHTPS_FORCECAL_AFTER_HOVERSETTING_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_FINGER_ABSORPTION_PROVISION_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_FINGER_ABSORPTION_DIST_THRESHOLD,	400);
	SHTPS_PARAM_DEF( SHTPS_FINGER_ABSORPTION_HOLD_TIME_MS,		200);

	#if defined(SHTPS_PINCHOUT_FAIL_FLICK_RESOLV_ENABLE)
		SHTPS_PARAM_DEF( SHTPS_PINCHOUT_FAIL_FLICK_RESOLV_DISABLE,	0);
		SHTPS_PARAM_DEF( SHTPS_PINCHOUT_DIST_THRESHOLD,				50);
		SHTPS_PARAM_DEF( SHTPS_PINCHOUT_HOLD_TIME_MS,				100);
	#endif /* SHTPS_PINCHOUT_FAIL_FLICK_RESOLV_ENABLE */
#endif /* SHTPS_FINGER_ABSORPTION_PROVISION_ENABLE */


/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_CLING_REJECTION_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_ENABLE,					1);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_ENABLE,					1);

	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_ANCHOR_AREA_X,			200);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_ANCHOR_AREA_Y,			200);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_ANCHOR_CNT_MAX,			100);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_BASE_POS_CHANGE_TIME,		100);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_REST_TIME,				1000);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_LEVEL_JUMP_THRESH_X,		200);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_LEVEL_JUMP_AREA_Y,		100);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_LEVEL_JUMP_CNT_MAX,		20);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_RIOT_JUMP_THRESH_X,		200);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_RIOT_JUMP_THRESH_Y,		200);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_RIOT_JUMP_CNT_MAX,		30);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_TU_HOVER_TD_TIME,		100);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_TU_HOVER_TD_DISTANCE_X,	600);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_TU_HOVER_TD_DISTANCE_Y,	700);

	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_MODE_1_ENABLE, 			0);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_MODE_2_ENABLE, 			1);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_MODE_3_ENABLE, 			1);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_HOVER_MODE_4_ENABLE, 			1);

	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_DETECT_THRESH_W,			60);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_JUMP_THRESH_X, 			200);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_JUMP_THRESH_Y, 			200);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_DETECT_THRESH_DIFF_W, 	50);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_DETECT_THRESH_DIFF_Z, 	30);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_JUMP_CNT_MAX, 			10);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_TU_NEGLECT_TIME_MS, 		100);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_STATIC_NUM_THRESH, 		3);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_STATIC_TIME_MS,			1000);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_STATIC_DIFF_W,			1);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_STATIC_DIFF_Z,			1);

	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_MODE_1_ENABLE, 			0);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_MODE_2_ENABLE, 			1);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_MODE_3_ENABLE, 			1);
	SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_FINGER_MODE_4_ENABLE, 			0);

	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_CLING_REJECT_LOG_ENABLE, 0);
		#define	SHTPS_LOG_CLING_REJECT(...)									\
			if(SHTPS_CLING_REJECT_LOG_ENABLE != 0){							\
				printk(KERN_DEBUG "[shtps] [cling_reject]" __VA_ARGS__);	\
			}
	#else
		#define	SHTPS_LOG_CLING_REJECT(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_CLING_REJECTION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_HOVER_HOST_JITTER_FILTER_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_HOVER_JITTER_FILTER_DISABLE,			0);
	SHTPS_PARAM_DEF( SHTPS_HOVER_JITTER_FILTER_THRESHOLD,		15);
	SHTPS_PARAM_DEF( SHTPS_HOVER_JITTER_FILTER_JUMP_THRESHOLD,	30);
	SHTPS_PARAM_DEF( SHTPS_HOVER_JITTER_FILTER_JUMP_COUNT,		5);
#endif /* SHTPS_HOVER_HOST_JITTER_FILTER_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_FINGER_WIDTH_MODERATION_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_FINGER_WIDTH_MODERATION_DISABLE,		0);
	SHTPS_PARAM_DEF( SHTPS_FINGER_WIDTH_GAIN_THRESHOLD,			10);
	SHTPS_PARAM_DEF( SHTPS_FINGER_WIDTH_MODERATION_RATIO,		5);
#endif	/* SHTPS_FINGER_WIDTH_MODERATION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_EDGE_FAIL_TOUCH_REJECTION_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_ENABLE,			1);
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_AREA_THRESH_X,	64);
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_AREA_THRESH_Y,	667);
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_DISTANCE,			591);
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_Z_RATIO,			99);
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_Z_RATIO_2,		91);
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_EFFECT_TIME,		500);

	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_TOP_AREA_THRESH_X,		265);
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_TOP_AREA_THRESH_Y,		5);
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_TOP_SIDE_AREA_THRESH_X,	60);
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_TOP_SIDE_AREA_THRESH_Y,	157);
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_TOP_AREA_THRESH_Z,		45);
	SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_TOP_AREA_THRESH_ZW_RATIO,	73);

	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_EDGE_FAIL_TOUCH_REJECT_LOG_ENABLE, 0);
	    #define	SHTPS_LOG_DBG_EDGE_FAIL_TOUCH_PRINT(...)						\
	        if(SHTPS_EDGE_FAIL_TOUCH_REJECT_LOG_ENABLE != 0){					\
	            printk(KERN_DEBUG "[shtps] [edge_fail_reject]" __VA_ARGS__);	\
	        }
	#else
		#define	SHTPS_LOG_DBG_EDGE_FAIL_TOUCH_PRINT(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_EDGE_FAIL_TOUCH_REJECTION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_TOUCHKEY_FAIL_TOUCH_REJECTION_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_TOUCHKEY_FAIL_TOUCH_REJECTION_DISABLE, 0);
#endif /* SHTPS_TOUCHKEY_FAIL_TOUCH_REJECTION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_GUARANTEE_SPI_ACCESS_IN_WAKE_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_SUSPEND_SPI_RESUME_FUNC_DELAY, 0);
#endif /* SHTPS_GUARANTEE_SPI_ACCESS_IN_WAKE_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_WAKEUP_FAIL_TOUCH_EVENT_REJECTION_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_WAKEUP_FAIL_TOUCH_EVENT_REJECT_REZERO_ENABLE, 1);
	
	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_WAKEUP_FAIL_TOUCH_EVENT_REJECT_LOG_ENABLE,    0);
		#define	SHTPS_LOG_WAKEUP_FAIL_TOUCH_EVENT_REJECT(...)					\
			if(SHTPS_WAKEUP_FAIL_TOUCH_EVENT_REJECT_LOG_ENABLE != 0){			\
				printk(KERN_DEBUG "[shtps] [wakeup_fail_event]" __VA_ARGS__);	\
			}
	#else
		#define	SHTPS_LOG_WAKEUP_FAIL_TOUCH_EVENT_REJECT(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_WAKEUP_FAIL_TOUCH_EVENT_REJECTION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_KEY_PROXIMITY_ASYNC_CHECK_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_KEY_PROXIMITY_DOWN_HOLD_TIME_MS, 500);
#endif /* SHTPS_KEY_PROXIMITY_ASYNC_CHECK_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_GRIP_FAIL_TOUCH_REJECTION_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_GRIP_FAIL_TOUCH_REJECT_ENABLE, 		1);
	SHTPS_PARAM_DEF( SHTPS_GRIP_FAIL_TOUCH_REJECT_AREA, 		20);
	SHTPS_PARAM_DEF( SHTPS_GRIP_FAIL_TOUCH_REJECT_W_THRESH_MIN, 8);
	SHTPS_PARAM_DEF( SHTPS_GRIP_FAIL_TOUCH_REJECT_W_THRESH_MAX, 18);
	SHTPS_PARAM_DEF( SHTPS_GRIP_FAIL_TOUCH_REJECT_Z_THRESH, 	60);
	SHTPS_PARAM_DEF( SHTPS_GRIP_FAIL_TOUCH_REJECT_W_THRESH, 	9);
	SHTPS_PARAM_DEF( SHTPS_GRIP_FAIL_FLICK_REJECT_ENABLE, 		1);
	SHTPS_PARAM_DEF( SHTPS_GRIP_FAIL_FLICK_REJECT_AREA, 		20);
	SHTPS_PARAM_DEF( SHTPS_GRIP_FAIL_FLICK_REJECT_W_THRESH, 	9);
	SHTPS_PARAM_DEF( SHTPS_GRIP_FAIL_FLICK_REJECT_DIST, 		300);

	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_GRIP_FAIL_TOUCH_REJECT_LOG_ENABLE, 0);
	    #define	SHTPS_LOG_DBG_GRIP_FAIL_TOUCH_PRINT(...)						\
	        if(SHTPS_GRIP_FAIL_TOUCH_REJECT_LOG_ENABLE != 0){					\
	            printk(KERN_DEBUG "[shtps] [grip_fail_reject]" __VA_ARGS__);	\
	        }
	#else
		#define	SHTPS_LOG_DBG_GRIP_FAIL_TOUCH_PRINT(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_GRIP_FAIL_TOUCH_REJECTION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_DIAGONAL_GHOST_CHECK_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_DIAGONAL_GHOST_CHECK_AREA, 				50);
	SHTPS_PARAM_DEF( SHTPS_DIAGONAL_GHOST_Z_THRESHOLD, 				255);
	SHTPS_PARAM_DEF( SHTPS_DIAGONAL_GHOST_TIMEOUT, 					500);
	SHTPS_PARAM_DEF( SHTPS_DIAGONAL_GHOST_CHECK_AFTER_TU_ENABLE, 	0);
#endif	/* SHTPS_DIAGONAL_GHOST_CHECK_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_GHOST_REJECTION_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_HOST_GHOST_REJECTION_ENABLE, 			0);
	SHTPS_PARAM_DEF( SHTPS_GHOST_THRESHOLD, 						30);
	SHTPS_PARAM_DEF( SHTPS_GHOST_CHECK_TOUCH_NUM_THRESH,		 	3);
#endif /* SHTPS_GHOST_REJECTION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_DRAG_SMOOTH_ENABLE )
	#define SHTPS_DRAG_HISTORY_SIZE_MAX 30
	SHTPS_PARAM_DEF( SHTPS_DRAG_SMOOTH_DISABLE, 					0);
	SHTPS_PARAM_DEF( SHTPS_DRAG_SMOOTH_LEAVE_MAX_DOT, 				10);
	SHTPS_PARAM_DEF( SHTPS_DRAG_SMOOTH_COUNT, 						5);
#endif /* SHTPS_DRAG_SMOOTH_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_SHIFT_EDGE_INWARD_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_SHIFT_EDGE_INWARD_OFFSET, 				10);
#endif /* SHTPS_SHIFT_EDGE_INWARD_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_PEN_DETECT_ENABLE)
	#define	SHTPS_PEN_ENABLE_F12_CTRL23_PARAM_ENABLE	0x07
	#define	SHTPS_PEN_ENABLE_F12_CTRL23_PARAM_DISABLE	0x05
	#define	SHTPS_PEN_ENABLE_F51_REG_ADDR				0x0422
	#define	SHTPS_PEN_ENABLE_F51_PARAM_ENABLE			0x0F
	#define	SHTPS_PEN_ENABLE_F51_PARAM_DISABLE			0x07
#endif /* #if defined(SHTPS_PEN_DETECT_ENABLE) */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_DYNAMIC_RESET_CONTROL_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_DYNAMIC_RESET_F54_COMMAND_ENABLE,		1);
	SHTPS_PARAM_DEF( SHTPS_DYNAMIC_RESET_COAXIAL_PEN_ENABLE,		0);
	SHTPS_PARAM_DEF( SHTPS_DYNAMIC_RESET_COAXIAL_PEN_TOUCH_COUNT,	20);

	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_DYNAMIC_RESET_LOG_ENABLE,			0);
		#define	SHTPS_LOG_DYNAMIC_RESET(...)								\
			if(SHTPS_DYNAMIC_RESET_LOG_ENABLE != 0){						\
				printk(KERN_DEBUG "[shtps] [dynamic_reset]" __VA_ARGS__);	\
			}
	#else
		#define	SHTPS_LOG_DYNAMIC_RESET(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_DYNAMIC_RESET_CONTROL_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_LGM_SPLIT_TOUCH_COMBINING_ENABLE )
	#define SHTPS_LGM_SPLIT_TOUCH_COMBINE_POS_HIST_CNT					3
	
	SHTPS_PARAM_DEF( SHTPS_LGM_SPLIT_TOUCH_COMBINE_ENABLE, 				1);
	SHTPS_PARAM_DEF( SHTPS_LGM_SPLIT_TOUCH_COMBINE_DIST_THRESH,			200);
	SHTPS_PARAM_DEF( SHTPS_LGM_SPLIT_TOUCH_COMBINE_DIST_THRESH_RATIO,	200);
	SHTPS_PARAM_DEF( SHTPS_LGM_SPLIT_TOUCH_COMBINE_TIME_THRESH, 		20);

	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_LGM_SPLIT_TOUCH_COMBINE_LOG_ENABLE, 0);
		#define	SHTPS_LOG_LGM_SPLIT_TOUCH_COMBINE(...)					\
			if(SHTPS_LGM_SPLIT_TOUCH_COMBINE_LOG_ENABLE != 0){			\
				printk(KERN_DEBUG "[shtps] [lgm split]" __VA_ARGS__);	\
			}
	#else
		#define	SHTPS_LOG_LGM_SPLIT_TOUCH_COMBINE(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */

#endif /* SHTPS_LGM_SPLIT_TOUCH_COMBINING_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_REPORT_TOOL_TYPE_LOCK_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_HOST_EVENT_TOOL_TYPE_LOCK_ENABLE, 		1);
#endif /* SHTPS_REPORT_TOOL_TYPE_LOCK_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_PEN_SCREEN_EDGE_DISABLE)
	SHTPS_PARAM_DEF( SHTPS_HOST_EVENT_BLOCK_EDGE_PEN_ENABLE, 	1);
	SHTPS_PARAM_DEF( SHTPS_PEN_EDGE_DISABLE_RANGE_X, 			20);
	SHTPS_PARAM_DEF( SHTPS_PEN_EDGE_DISABLE_RANGE_Y, 			0);
#endif /* SHTPS_PEN_SCREEN_EDGE_DISABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_MULTITOUCH_PEN_GHOST_REJECTION_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_MULTITOUCH_PEN_GHOST_REJECTION, 			0);
	SHTPS_PARAM_DEF( SHTPS_MULTITOUCH_PEN_GHOST_Z_THRESHOLD_MIN, 	9);
	SHTPS_PARAM_DEF( SHTPS_MULTITOUCH_PEN_GHOST_Z_THRESHOLD_MAX, 	50);
#endif	/* SHTPS_MULTITOUCH_PEN_GHOST_REJECTION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_HOVER_REJECT_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_HOST_HOVER_DETECT_REJECTION_ENABLE, 					1);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_EDGE_AREA, 								60);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_PEN_TD_MOVE_THRESH, 					20);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_1_PEN_CHATT_CNT, 						4);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_1_PEN_CHATT_Z_THRESHOLD_MIN,			8);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_1_PEN_CHATT_Z_THRESHOLD_MAX,			32);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_1_PEN_CHATT_TAP_CNT,					4);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_2_FINGER_Z_THRESHOLD, 					30);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_3_1_Z_THRESHOLD, 						2);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_3_1_IGNORE_TIME, 						30);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_3_2_Z_THRESHOLD, 						3);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_3_2_IGNORE_TIME, 						20);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_3_3_Z_THRESHOLD, 						7);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_3_3_IGNORE_TIME, 						10);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_4_MOVE_THRESHOLD, 						30);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_4_PEN_Z_THRESHOLD,	 					10);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_4_FINGER_Z_THRESHOLD,	 				30);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_5_FINGER_Z_THRESHOLD,	 				35);

	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_FINGER_TU_PEN_IGNORE_TIME, 				40);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_FINGER_TU_FINGER_IGNORE_TIME, 			35);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_FINGER_TU_FINGER_TD_IGNORE_TIME, 		40);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_FINGER_TU_PEN_IGNORE_MOVE_THRESHOLD,	100);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_FINGER_TU_FINGER_IGNORE_TD_COUNT, 		3);
	SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_READ_TOUCH_EVENT_POLLING_TIME_MS, 		0);

	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_HOVER_REJECT_LOG_ENABLE, 0);
		#define	SHTPS_LOG_HOVER_REJECT(...)									\
			if(SHTPS_HOVER_REJECT_LOG_ENABLE != 0){							\
				printk(KERN_DEBUG "[shtps] [hover_reject]" __VA_ARGS__);	\
			}
	#else
		#define	SHTPS_LOG_HOVER_REJECT(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_HOVER_REJECT_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_PEN_EVENT_FAIL_CONTINUE_REJECT_ENABLE)
	#define SHTPS_PEN_Z_HIST_MAX									32
	#define SHTPS_PEN_FAIL_CONT_HOLD_INFO_NUM						32

	SHTPS_PARAM_DEF( SHTPS_HOST_PEN_CONNECT_REJECTION_ENABLE, 		0);
	SHTPS_PARAM_DEF( SHTPS_PEN_EVENT_FAIL_CONTINUE_REJECT_TYPE, 	2);
	SHTPS_PARAM_DEF( SHTPS_PEN_Z_HIST_COUNT_MAX, 					2);
	SHTPS_PARAM_DEF( SHTPS_PEN_EFFECT_Z_DIFF_THRESHOLD, 			3);
	SHTPS_PARAM_DEF( SHTPS_PEN_EFFECT_Z_AVERAGE_PERCENT, 			70);
	SHTPS_PARAM_DEF( SHTPS_PEN_FORCE_EFFECT_Z_THRESHOLD, 			100);
	SHTPS_PARAM_DEF( SHTPS_PEN_CHATTERING_TIME_MS, 					40);
	SHTPS_PARAM_DEF( SHTPS_PEN_Z_HIST_COUNT_2ND_MAX, 				2);
	SHTPS_PARAM_DEF( SHTPS_PEN_EFFECT_Z_DIFF_MIN_THRESHOLD, 		2);
	SHTPS_PARAM_DEF( SHTPS_PEN_EFFECT_Z_MAX_DIVIDE, 				2);
	SHTPS_PARAM_DEF( SHTPS_PEN_EFFECT_Z_MAX_DIVIDE_THRESHOLD, 		4);
	SHTPS_PARAM_DEF( SHTPS_PEN_CHATTERING_COUNT_MAX, 				1);
	SHTPS_PARAM_DEF( SHTPS_PEN_CHATTERING_CANCEL_Z_THRESHOLD, 		4);
	SHTPS_PARAM_DEF( SHTPS_PEN_CHATTERING_CANCEL_Z_MAX_PERCENT, 	70);

	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_PEN_EVENT_FAIL_CONTINUE_LOG_ENABLE, 0);
		#define	SHTPS_LOG_PEN_EVENT_FAIL_CONTINUE(...)							\
			if(SHTPS_PEN_EVENT_FAIL_CONTINUE_LOG_ENABLE != 0){					\
				printk(KERN_DEBUG "[shtps] [pen_fail_continue]" __VA_ARGS__);	\
			}
	#else
		#define	SHTPS_LOG_PEN_EVENT_FAIL_CONTINUE(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_PEN_EVENT_FAIL_CONTINUE_REJECT_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_PEN_POS_JUMP_REJECT_ENABLE )
	#define SHTPS_PEN_POS_JUMP_HIST_MAX									10
	#define SHTPS_PEN_POS_JUMP_HOLD_MAX									20

	SHTPS_PARAM_DEF( SHTPS_HOST_PEN_JUMP_REJECTION_ENABLE, 				0);
	SHTPS_PARAM_DEF( SHTPS_PEN_POS_JUMP_ACCELERATION_THRESHOLD, 		50000);
	SHTPS_PARAM_DEF( SHTPS_PEN_POS_JUMP_HOLD_ACCELERATION_THRESHOLD, 	100);
	SHTPS_PARAM_DEF( SHTPS_PEN_POS_JUMP_HIST_COUNT_MAX, 				3);
	SHTPS_PARAM_DEF( SHTPS_PEN_POS_JUMP_HOLD_EVENT_TIME_MAX, 			70);
	SHTPS_PARAM_DEF( SHTPS_PEN_POS_JUMP_TD_CHECK_COUNT_MAX, 			3);
	SHTPS_PARAM_DEF( SHTPS_PEN_POS_JUMP_HOLD_DRAG_THRESHOLD_MIN, 		100);
	SHTPS_PARAM_DEF( SHTPS_PEN_POS_JUMP_HOLD_DRAG_THRESHOLD_MAX, 		300);

	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_PEN_POS_JUMP_REJECT_LOG_ENABLE, 0);
		#define	SHTPS_LOG_PEN_POS_JUMP_REJECT(...)								\
			if(SHTPS_PEN_POS_JUMP_REJECT_LOG_ENABLE != 0){						\
				printk(KERN_DEBUG "[shtps] [pen_jump_reject]" __VA_ARGS__);		\
			}
	#else
		#define	SHTPS_LOG_PEN_POS_JUMP_REJECT(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_PEN_POS_JUMP_REJECT_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_COAXIAL_GHOST_REJECTION_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_COAXIAL_GHOST_REJECT_ENABLE, 			1);
	SHTPS_PARAM_DEF( SHTPS_COAXIAL_GHOST_REJECT_DRAG_MAX_NUM,		5);
	SHTPS_PARAM_DEF( SHTPS_COAXIAL_GHOST_REJECT_DRAG_YDIFF_COND,	8);
	SHTPS_PARAM_DEF( SHTPS_COAXIAL_GHOST_REJECT_YDIFF_THRESH_MV,	150);
	SHTPS_PARAM_DEF( SHTPS_COAXIAL_GHOST_REJECT_YDIFF_THRESH_MV_ST,	15);
	SHTPS_PARAM_DEF( SHTPS_COAXIAL_GHOST_REJECT_YDIFF_THRESH_TD,	150);
	SHTPS_PARAM_DEF( SHTPS_COAXIAL_GHOST_REJECT_YDIFF_THRESH_TD_ST,	5);
	SHTPS_PARAM_DEF( SHTPS_COAXIAL_GHOST_REJECT_Z_THRESH_MV, 		50);
	SHTPS_PARAM_DEF( SHTPS_COAXIAL_GHOST_REJECT_Z_THRESH_MV_ST, 	65);
	SHTPS_PARAM_DEF( SHTPS_COAXIAL_GHOST_REJECT_Z_THRESH_TD, 		50);
	SHTPS_PARAM_DEF( SHTPS_COAXIAL_GHOST_REJECT_Z_THRESH_TD_ST,		60);
#endif /* SHTPS_COAXIAL_GHOST_REJECTION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_PINCH_FAIL_RESPONSE_REJECTION_ENABLE)

	SHTPS_PARAM_DEF( SHTPS_PINCH_FAIL_RESPONSE_REJECT_ENABLE, 			1);
	SHTPS_PARAM_DEF( SHTPS_PINCH_FAIL_FINGER_1ST_DISTANCE_THRESH, 		500);
	SHTPS_PARAM_DEF( SHTPS_PINCH_FAIL_FINGER_2ND_DISTANCE_THRESH, 		430);
	SHTPS_PARAM_DEF( SHTPS_SEGMENTATION_AGGRESSIVENESS_SET_VAL, 		0xC0);


	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_PINCH_FAIL_RESPONSE_REJECT_LOG_ENABLE, 		0);
	    #define	SHTPS_LOG_DBG_SHTPS_PINCH_FAIL_RESPONSE_PRINT(...)				\
	        if(SHTPS_PINCH_FAIL_RESPONSE_REJECT_LOG_ENABLE != 0){				\
	            printk(KERN_DEBUG "[shtps] [pinch_fail_reject]" __VA_ARGS__);	\
	        }
	#else
		#define	SHTPS_LOG_DBG_SHTPS_PINCH_FAIL_RESPONSE_PRINT(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_PINCH_FAIL_RESPONSE_REJECTION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_PINCHOUT_OUTSET_DISTORT_REJECTION_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_PINCHOUT_OUTSET_DISTORT_REJECT_ENABLE, 			1);
	SHTPS_PARAM_DEF( SHTPS_PINCHOUT_OUTSET_DISTORT_REJECT_Z_REDUCE_THRESH, 	10);
	SHTPS_PARAM_DEF( SHTPS_PINCHOUT_OUTSET_DISTORT_REJECT_DISTANCE_THRESH, 	340);

	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_PINCHOUT_OUTSET_DISTORT_REJECT_LOG_ENABLE, 	0);
	    #define	SHTPS_LOG_DBG_PINCHOUT_DISTORT_PRINT(...)				\
	        if(SHTPS_PINCHOUT_OUTSET_DISTORT_REJECT_LOG_ENABLE != 0){	\
	            printk(KERN_DEBUG "[shtps] [pinch_out]" __VA_ARGS__);	\
	        }
	#else
		#define	SHTPS_LOG_DBG_PINCHOUT_DISTORT_PRINT(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_PINCHOUT_OUTSET_DISTORT_REJECTION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_BASELINE_OFFSET_DISABLE_WAIT_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_BASELINE_OFFSET_CBC_READ_AFTER_WAIT, 		30);
	SHTPS_PARAM_DEF( SHTPS_BASELINE_OFFSET_CBC_SET_AFTER_WAIT, 			30);
#endif /* SHTPS_BASELINE_OFFSET_DISABLE_WAIT_ENABLE */


/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_TOP_EDGE_FAIL_TOUCH_REJECTION_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_TOP_EDGE_FAIL_TOUCH_REJECT_ENABLE, 		1);
	SHTPS_PARAM_DEF( SHTPS_TOP_EDGE_FAIL_TOUCH_REJECT_AREA, 		30);
	SHTPS_PARAM_DEF( SHTPS_TOP_EDGE_FAIL_TOUCH_REJECT_WX_THRESH_MAX, 	18);
	SHTPS_PARAM_DEF( SHTPS_TOP_EDGE_FAIL_TOUCH_REJECT_WX_THRESH_MIN, 	8);
	SHTPS_PARAM_DEF( SHTPS_TOP_EDGE_FAIL_TOUCH_REJECT_Z_THRESH, 	60);

	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_TOP_EDGE_FAIL_TOUCH_REJECT_LOG_ENABLE, 0);
	    #define	SHTPS_LOG_DBG_TOP_EDGE_FAIL_TOUCH_PRINT(...)						\
	        if(SHTPS_TOP_EDGE_FAIL_TOUCH_REJECT_LOG_ENABLE != 0){					\
	            printk(KERN_DEBUG "[shtps] [top_edge_fail_reject]" __VA_ARGS__);	\
	        }
	#else
		#define	SHTPS_LOG_DBG_GRIP_FAIL_TOUCH_PRINT(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_TOP_EDGE_FAIL_TOUCH_REJECTION_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#endif /* __SHTPS_CFG_TM2945_001_H__ */
