ccflags-y += -Idrivers/media/platform/msm/camera_v2-ebz
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ebz/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ebz/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
